# CI configuration file for wal2json
# https://cirrus-ci.com/

env:
  DEBIAN_FRONTEND: noninteractive
  LANG: C

task:
  name: Linux (Ubuntu)
  matrix:
    - container:
        image: ubuntu:22.04
  env:
    matrix:
      - PGVERSION: 16
      - PGVERSION: 15
      - PGVERSION: 14
      - PGVERSION: 13
      - PGVERSION: 12
  setup_script:
    - apt-get update
    - apt-get -y install curl gnupg lsb-release ca-certificates locales
    - echo "en_US.UTF-8 UTF-8" | tee -a /etc/locale.gen
    - locale-gen
    - LANG=en_US.UTF-8
    - install -d /usr/share/postgresql-common/pgdg
    - curl -o /usr/share/postgresql-common/pgdg/apt.postgresql.org.asc --fail https://www.postgresql.org/media/keys/ACCC4CF8.asc
    - echo "deb [signed-by=/usr/share/postgresql-common/pgdg/apt.postgresql.org.asc] https://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" | tee /etc/apt/sources.list.d/pgdg.list
    - apt-get update
    - apt-get -y install postgresql-common
    - echo "wal_level = logical" | tee -a /etc/postgresql-common/createcluster.conf
    - echo "initdb_options = '--locale en_US.UTF-8'" | tee -a /etc/postgresql-common/createcluster.conf
    - apt-get -y install gcc make postgresql-$PGVERSION postgresql-server-dev-$PGVERSION
    - pg_lsclusters
    - pg_ctlcluster 16 main start
    - chown -R postgres .
  build_script:
    - PATH=/usr/lib/postgresql/$PGVERSION/bin:$PATH
    - su postgres -c "make"
    - make install
  test_script:
    - PATH=/usr/lib/postgresql/$PGVERSION/bin:$PATH
    - su postgres -c "make installcheck"
  on_failure:
    testrun_artifacts:
      paths:
        - "**/*.log"
        - "**/*.diffs"
        - "**/*.out"
      type: text/plain

task:
  name: FreeBSD
  freebsd_instance:
    image_family: freebsd-14-0
  env:
    matrix:
      - PGVERSION: 16
#      - PGVERSION: 15
#      - PGVERSION: 14
#      - PGVERSION: 13
#      - PGVERSION: 12
  setup_script:
    - pkg install -y gcc gmake postgresql$PGVERSION-server sudo
    - /usr/local/etc/rc.d/postgresql initdb
    - echo "wal_level = logical" | tee -a /var/db/postgres/data$PGVERSION/postgresql.conf
    - service postgresql start
    - which pg_ctl
    - ls -laR /var/db
    - chown -R postgres .
  build_script:
    - su postgres -c "make"
    - make install
  test_script:
    - su postgres -c "make installcheck"
  on_failure:
    testrun_artifacts:
      paths:
        - "**/*.log"
        - "**/*.diffs"
        - "**/*.out"
      type: text/plain
