sudo: required

branches:
  only:
    - master
    - pg_logical_emit_message
    - travis-builds

env:
  matrix:
    - PG_VERSION=9.4
    - PG_VERSION=9.5
    - PG_VERSION=9.6
    - PG_VERSION=10

language: c

services:
  - docker

before_install:
  - docker pull dpirotte/postgres-dev:jessie

script:
  - docker run --rm -v $PWD:/build -w /build -it -e PG_CONFIG=/usr/lib/postgresql/$PG_VERSION/bin/pg_config dpirotte/postgres-dev:jessie bash -c "pg_ctlcluster $PG_VERSION main start && make clean all install installcheck"

